// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6iLP2vmw8XZL1Zn6awM1KFG4m_W3nBSQ',
    appId: '1:992814604490:web:ef17b5dd2f6e2337e41433',
    messagingSenderId: '992814604490',
    projectId: 'flutterfirevalenjulyo',
    authDomain: 'flutterfirevalenjulyo.firebaseapp.com',
    storageBucket: 'flutterfirevalenjulyo.appspot.com',
    measurementId: 'G-392YWQC0EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBImndgP3NsJNqWvmxgl2FTQ2d7JWlUs8I',
    appId: '1:992814604490:android:e577cd11302d0568e41433',
    messagingSenderId: '992814604490',
    projectId: 'flutterfirevalenjulyo',
    storageBucket: 'flutterfirevalenjulyo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfROQTwpxqyZk63ltpdgTDU18kuQSOYdw',
    appId: '1:992814604490:ios:a0ea2bc90974680fe41433',
    messagingSenderId: '992814604490',
    projectId: 'flutterfirevalenjulyo',
    storageBucket: 'flutterfirevalenjulyo.appspot.com',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfROQTwpxqyZk63ltpdgTDU18kuQSOYdw',
    appId: '1:992814604490:ios:a0ea2bc90974680fe41433',
    messagingSenderId: '992814604490',
    projectId: 'flutterfirevalenjulyo',
    storageBucket: 'flutterfirevalenjulyo.appspot.com',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6iLP2vmw8XZL1Zn6awM1KFG4m_W3nBSQ',
    appId: '1:992814604490:web:32f9423b0da42e30e41433',
    messagingSenderId: '992814604490',
    projectId: 'flutterfirevalenjulyo',
    authDomain: 'flutterfirevalenjulyo.firebaseapp.com',
    storageBucket: 'flutterfirevalenjulyo.appspot.com',
    measurementId: 'G-00QDGXPNLM',
  );
}
