// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPJvQ-w7aWhOlcdRgwS9H1pUq2RqiGL_s',
    appId: '1:947431069235:web:88c3fe8216ba2378973546',
    messagingSenderId: '947431069235',
    projectId: 'notes-dd181',
    authDomain: 'notes-dd181.firebaseapp.com',
    storageBucket: 'notes-dd181.appspot.com',
    measurementId: 'G-BDYJ2DXMNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb1aG2Jbo1orgDmj90VqCCaeNv6rITXm8',
    appId: '1:947431069235:android:f5b68e68ba69ec29973546',
    messagingSenderId: '947431069235',
    projectId: 'notes-dd181',
    storageBucket: 'notes-dd181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgASINHs2I4Bq_y9j8X76kdhtPmqKG7xA',
    appId: '1:947431069235:ios:18b2f6a1da8dd9a7973546',
    messagingSenderId: '947431069235',
    projectId: 'notes-dd181',
    storageBucket: 'notes-dd181.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgASINHs2I4Bq_y9j8X76kdhtPmqKG7xA',
    appId: '1:947431069235:ios:18b2f6a1da8dd9a7973546',
    messagingSenderId: '947431069235',
    projectId: 'notes-dd181',
    storageBucket: 'notes-dd181.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPJvQ-w7aWhOlcdRgwS9H1pUq2RqiGL_s',
    appId: '1:947431069235:web:7f42a49c93ad3681973546',
    messagingSenderId: '947431069235',
    projectId: 'notes-dd181',
    authDomain: 'notes-dd181.firebaseapp.com',
    storageBucket: 'notes-dd181.appspot.com',
    measurementId: 'G-HMQTZZYPC6',
  );
}
